activation: relu
activation_output: sigmoid
batch_size: 64
checkpoint_monitor: accuracy
checkpoint_save_frequency: 5
data_url: https://storage.googleapis.com/tf-datasets/titanic/train.csv
dropout: 0.0
epochs: 10
h_layers: 3
input_size: 33
l1: 0.0001
l2: 0.0001
loss: binary_crossentropy
lr: 0.0004
metrics:
- accuracy
name: BINARY_CLASSIFICATION
optimizer: adam
output_size: 1
target: alone
units: 16
use_bias: false
